---@meta
-- MTAX Lua API — server natives
-- Generated by mtax-vscode (tools/generate-api.mjs). Do not edit by hand.

--- Deletes a key from an element.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#removeelementdata
---@param theElement element
---@param key string
---@return boolean # `true` if the key existed and was deleted, `false` if it was not set on that element.
function removeElementData(theElement, key) end

--- Subscribes a player to a key's updates.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#addelementdatasubscriber
---@param theElement element
---@param key string
---@param thePlayer player
---@return boolean # `true` if the subscription was made, `false` otherwise.
function addElementDataSubscriber(theElement, key, thePlayer) end

--- Unsubscribes a player from a key.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#removeelementdatasubscriber
---@param theElement element
---@param key string
---@param thePlayer player
---@return boolean # `true` if the player was subscribed, `false` otherwise. The client keeps the last value it received.
function removeElementDataSubscriber(theElement, key, thePlayer) end

--- Checks whether a player is subscribed to a key.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#haselementdatasubscriber
---@param theElement element
---@param key string
---@param thePlayer player
---@return boolean # `true` if subscribed, `false` otherwise.
function hasElementDataSubscriber(theElement, key, thePlayer) end

--- Adds or removes an element from the visibility list.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#setelementvisibleto
---@param theElement element The blip or marker.
---@param visibleTo element Player (or `root`) to add to or remove from the list.
---@param visible boolean `true` adds, `false` removes.
---@return boolean # `true` if the list changed, `false` otherwise. Types that have no per-player visibility always return `false`.
function setElementVisibleTo(theElement, visibleTo, visible) end

--- Empties the visibility list.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#clearelementvisibleto
---@param theElement element
---@return boolean # `true` for any blip or marker, even when the list was already empty; `false` for every other type.
function clearElementVisibleTo(theElement) end

--- Checks whether an element is on the visibility list.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#iselementvisibleto
---@param theElement element
---@param visibleTo element
---@return boolean # `true` if `visibleTo` is literally on the list, `false` otherwise. Elements with no per-player visibility always answer `true`.
function isElementVisibleTo(theElement, visibleTo) end

--- Creates a copy of an existing element.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#cloneelement
---@param theElement element Element to copy.
---@param x? number
---@param y? number
---@param z? number
---@param cloneChildren? boolean Also clone the source's direct children.
---@return element # the clone, or `false` if the element cannot be cloned.
function cloneElement(theElement, x, y, z, cloneChildren) end

--- Returns the name of the map area an element is standing in.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/element/#getelementzonename
---@param theElement element Element to locate.
---@param citiesOnly? boolean With `true`, returns just the city name instead of the neighbourhood.
---@return string # the area name, or `false` for an invalid element. A valid element always yields some string: outside the known map the result is `"Unknown"`.
function getElementZoneName(theElement, citiesOnly) end

--- Checks whether this resource has a key bound to a function on a player's client.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#iskeybound
---@param thePlayer player Player to check.
---@param key string Key name. Case does not matter.
---@param keyState? string `"down"` or `"up"`. Any other value, or leaving it out, accepts both states.
---@param handler? function Accepted but ignored: matching uses only the key and the state.
---@return boolean # `true` if a matching bind exists, `false` otherwise or if the first argument is not a player.
function isKeyBound(thePlayer, key, keyState, handler) end

--- Disconnects a player from the server.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#kickplayer
---@param thePlayer player Player to kick.
---@param reason? string Reason shown to the player and written to the console log.
---@return boolean # `true` if the player was disconnected; `false` if the first argument is not a player, or if they are no longer connected.
function kickPlayer(thePlayer, reason) end

--- Returns a player's blur level.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayerblurlevel
---@param thePlayer player
---@return number # the current level, 0 to 255. Until anything has been set, the value is `36`. Returns `false` if the element is not a player.
function getPlayerBlurLevel(thePlayer) end

--- Sets how blurred a player's screen is.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setplayerblurlevel
---@param thePlayer element Player, or an element above them in the tree.
---@param level number Blur strength, 0 to 255.
---@return boolean # `true` on success. A level outside 0-255 raises an error and returns `false`.
function setPlayerBlurLevel(thePlayer, level) end

--- Reads the handling currently in force for a model.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getmodelhandling
---@param model number
---@return table # the model's handling table. An invalid ID returns `false` with the error "Invalid model id".
function getModelHandling(model) end

--- Changes the handling of every vehicle of a model.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#setmodelhandling
---@param model number Model ID.
---@param property? string Property to change. Left out (or `nil`), the whole model goes back to factory values.
---@param value? any New value. `nil` restores just that property.
---@return boolean
function setModelHandling(model, property, value) end

--- Sends the vehicle back to its respawn point right now.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#respawnvehicle
---@param theVehicle vehicle
---@return boolean
function respawnVehicle(theVehicle) end

--- Turns automatic respawning on or off.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#togglevehiclerespawn
---@param theVehicle vehicle
---@param enabled boolean
---@return boolean
function toggleVehicleRespawn(theVehicle, enabled) end

--- Sets where the vehicle comes back to.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#setvehiclerespawnposition
---@param theVehicle vehicle Vehicle to configure.
---@param x number
---@param y number
---@param z number
---@param rx? number
---@param ry? number
---@param rz? number
---@return boolean
function setVehicleRespawnPosition(theVehicle, x, y, z, rx, ry, rz) end

--- Returns the respawn point.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getvehiclerespawnposition
---@param theVehicle vehicle
---@return number, number, number # `x`, `y`, `z`.
function getVehicleRespawnPosition(theVehicle) end

--- Sets just the respawn rotation.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#setvehiclerespawnrotation
---@param theVehicle vehicle
---@param rx number
---@param ry number
---@param rz number
---@return boolean
function setVehicleRespawnRotation(theVehicle, rx, ry, rz) end

--- Returns the respawn rotation.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getvehiclerespawnrotation
---@param theVehicle vehicle
---@return number, number, number # `rx`, `ry`, `rz`.
function getVehicleRespawnRotation(theVehicle) end

--- Sets how long the vehicle stays wrecked before coming back.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#setvehiclerespawndelay
---@param theVehicle vehicle
---@param milliseconds number
---@return boolean
function setVehicleRespawnDelay(theVehicle, milliseconds) end

--- Returns the post-explosion respawn delay.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getvehiclerespawndelay
---@param theVehicle vehicle
---@return number # the delay in milliseconds. The default is `5000`.
function getVehicleRespawnDelay(theVehicle) end

--- Sets how long the vehicle can sit empty before coming back.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#setvehicleidlerespawndelay
---@param theVehicle vehicle
---@param milliseconds number
---@return boolean
function setVehicleIdleRespawnDelay(theVehicle, milliseconds) end

--- Returns the idle respawn delay.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getvehicleidlerespawndelay
---@param theVehicle vehicle
---@return number # the delay in milliseconds. The default is `0`.
function getVehicleIdleRespawnDelay(theVehicle) end

--- Sets a new respawn point and moves the vehicle straight to it.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#spawnvehicle
---@param theVehicle vehicle Vehicle to move.
---@param x number
---@param y number
---@param z number
---@param rx? number
---@param ry? number
---@param rz? number
---@return boolean
function spawnVehicle(theVehicle, x, y, z, rx, ry, rz) end

--- Tells you whether automatic respawning is on.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#isvehiclerespawnable
---@param theVehicle vehicle
---@return boolean
function isVehicleRespawnable(theVehicle) end

--- Clears the countdown since the explosion, postponing the automatic respawn.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#resetvehicleexplosiontime
---@param theVehicle vehicle
---@return boolean
function resetVehicleExplosionTime(theVehicle) end

--- Clears the idle countdown, postponing the abandoned-vehicle respawn.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#resetvehicleidletime
---@param theVehicle vehicle
---@return boolean
function resetVehicleIdleTime(theVehicle) end

--- Lists every vehicle on the server with a given model.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/vehicle/#getvehiclesoftype
---@param model number
---@return table # a sequential table of elements. Empty when there are none.
function getVehiclesOfType(model) end

--- Fires an event on players' machines.
---
--- Side: **server** · Trust: **bridge**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/event/#triggerclientevent
---@param sendTo element|table A player, a table of players, or a parent element — in which case every player below it receives the event. Pass `root` to reach everyone.
---@param eventName string Event to fire on the client.
---@param baseElement element Element the event comes from; becomes `source` on the client.
---@param ... any
---@return boolean # `true` if the send was accepted, `false` if the event name is empty.
function triggerClientEvent(sendTo, eventName, baseElement, ...) end

--- Opens a connection to a database.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbconnect
---@param type string `"sqlite"`, `"mysql"` or `"mariadb"`.
---@param target string The database file for `sqlite`, or the address of the server for `mysql`/`mariadb`. See below.
---@param username? string Login user. Ignored by `sqlite`.
---@param password? string Login password. Ignored by `sqlite`.
---@param options? string Extra settings, as `key=value` pairs.
---@return any # the connection element, or `false` if the type is none of the three, no `target` was given, a SQLite path escapes the `databases` folder or cannot be opened, or the MySQL server refuses the connection. On failure the reason is written to the debug console; nothing is raised, so your script keeps running and you check the return value yourself.
function dbConnect(type, target, username, password, options) end

--- Starts a query and gives you a handle to read the result with `dbPoll`.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbquery
---@param callback? function Optional. Called once the result is ready.
---@param arguments? table Optional, and only alongside `callback`. Values passed to the function after the handle.
---@param theConnection any Element returned by `dbConnect`.
---@param sql string Query to run.
---@param ... any
---@return query # the query handle (a number), or `false` if the connection element isn't usable or the query string is missing.
function dbQuery(callback, arguments, theConnection, sql, ...) end

--- Runs a SQL statement that you don't need rows back from.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbexec
---@param theConnection any Element returned by `dbConnect`.
---@param sql string Statement to run.
---@param ... any
---@return boolean # `true` once the statement has been handed to the background worker, `false` if the first argument isn't a usable connection element.
function dbExec(theConnection, sql, ...) end

--- Calls a function exported by another MTAX server over its HTTP interface.
--- 
--- Naming the server, the resource and the function:
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/http/#callremote
---@param host string Address and HTTP port of the other server, for example `"127.0.0.1:22005"`.
---@param queueName? string Queue name. Requests in the same queue run one at a time.
---@param attempts? number How many times to try connecting.
---@param timeout? number Connection timeout, in milliseconds.
---@param resourceName string Name of the remote resource.
---@param functionName string Name of the exported function.
---@param callback function Called when the response arrives. Required.
---@param ... any
---@return boolean # `true` if the request was queued. `false`, with the reason in the debug console, if the argument list matches neither form.
function callRemote(host, queueName, attempts, timeout, resourceName, functionName, callback, ...) end

--- Lists every resource the server has found.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresources
---@return table # a table of resources in alphabetical order, stopped ones included.
function getResources() end

--- Reads a field declared in a resource's manifest.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresourceinfo
---@param theResource resource Resource to look up.
---@param key string Key inside `resource_info`.
---@return string # the value as a string, or `false` when the key does not exist.
function getResourceInfo(theResource, key) end

--- When the resource was loaded.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresourceloadtime
---@param theResource resource
---@return number # a point in time in seconds, on the same scale `getRealTime` uses. Returns `false` for an unknown resource, or when the time is not known.
function getResourceLoadTime(theResource) end

--- When the resource was last started.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresourcelaststarttime
---@param theResource resource
---@return number # a point in time in seconds, on the same scale as `getRealTime`; the string `"never"` if the resource has never been started; `false` for an unknown resource.
function getResourceLastStartTime(theResource) end

--- Explains why the last start failed.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresourceloadfailurereason
---@param theResource resource
---@return string # the error message, or an **empty string** when the last start did not fail. For an unknown resource it returns `false`.
function getResourceLoadFailureReason(theResource) end

--- Returns the chain of organisational folders in which a resource was found.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#getresourceorganizationalpath
---@param theResource resource
---@return string # the category path relative to `resources/`, separated by `/`; an empty string for a resource directly under `resources/`; or `false` if the resource does not exist.
function getResourceOrganizationalPath(theResource) end

--- Starts a resource.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#startresource
---@param theResource resource
---@return boolean # `true` if the resource came up, `false` if it does not exist or was already running.
function startResource(theResource) end

--- Schedules a resource to stop.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#stopresource
---@param theResource resource
---@return boolean # `true` if the stop was **scheduled**, `false` if the resource does not exist or was not running.
function stopResource(theResource) end

--- Schedules a resource to restart.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#restartresource
---@param theResource resource
---@return boolean # `true` if the restart was scheduled. Returns `false` if the resource does not exist or is stopped — use `startResource` to bring a stopped resource up.
function restartResource(theResource) end

--- Re-reads the `resources/` folder, picking up new resources, removed ones and changed manifests.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/resource/#refreshresources
---@return boolean # `true` when the re-scan was scheduled.
function refreshResources() end

--- Returns the server's public name.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#getservername
---@return string # the name configured in `server.cfg`, or an empty string if none is set.
function getServerName() end

--- Returns the simultaneous player limit.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#getmaxplayers
---@return number # the value of `sv_maxclients`.
function getMaxPlayers() end

--- Returns the port the game server listens on.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#getserverport
---@return number
function getServerPort() end

--- Returns the port of the HTTP server that delivers resource files to clients.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#getserverhttpport
---@return number
function getServerHttpPort() end

--- Shuts the server down.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#shutdown
---@param reason? string Why the server is going down. An empty or blank string falls back to the default.
---@param exitCode? integer The process exit code. Leave it out to keep whatever the server would have returned.
---@return boolean # `true` when the shutdown was accepted.
function shutdown(reason, exitCode) end

--- Throws away a result you are not going to read.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbfree
---@param theQuery query Handle returned by `dbQuery`.
---@return boolean # `true` if there was something to drop, `false` if the handle had already been read with `dbPoll`, had already been freed, or was never valid.
function dbFree(theQuery) end

--- Collects the result of a query.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbpoll
---@param theQuery query Handle returned by `dbQuery`.
---@param timeout? number How long to wait for the result, in milliseconds. `0` checks once and returns straight away. A positive number waits up to that many milliseconds. A negative number, `-1` by convention, waits for as long as the query takes.
---@param multipleResults? boolean `true` returns one entry per statement in the query instead of only the first.
---@return table, number, number # on success, three values:
function dbPoll(theQuery, timeout, multipleResults) end

--- Builds a SQL string with the values already escaped in place of the `?` placeholders.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/database/#dbpreparestring
---@param theConnection any Element returned by `dbConnect`.
---@param sql string Query with `?` where the values go.
---@param ... any
---@return string # the finished query as a string, or `false` if the connection element isn't usable.
function dbPrepareString(theConnection, sql, ...) end

--- Returns the gravity applied to the ped.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#getpedgravity
---@param thePed ped
---@return number # the gravity, or `false` if the element is not a ped. The default is `0.008`.
function getPedGravity(thePed) end

--- Makes the ped reload the weapon it is holding.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#reloadpedweapon
---@param thePed ped
---@return boolean # `true` if the reload started. Returns `false` if the element is invalid or an event handler cancels the reload.
function reloadPedWeapon(thePed) end

--- Makes the ped choke, as if it had walked into teargas or an extinguisher.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#setpedchoking
---@param thePed ped
---@param choking boolean
---@return boolean # `true` if at least one ped was changed.
function setPedChoking(thePed, choking) end

--- Sets the ped's gravity.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#setpedgravity
---@param thePed ped Ped, or a parent element.
---@param gravity number Value between `-1` and `1`.
---@return boolean # `true` if at least one ped was changed. Values outside `-1`–`1` return `false`, and setting the gravity a ped already has also returns `false`.
function setPedGravity(thePed, gravity) end

--- Puts a jetpack on the ped, or takes it off.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#setpedwearingjetpack
---@param thePed ped
---@param jetpack boolean
---@return boolean # `true` if at least one ped was changed.
function setPedWearingJetpack(thePed, jetpack) end

--- Returns how long the pickup waits before coming back.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/pickup/#getpickuprespawninterval
---@param thePickup pickup
---@return number # the interval in milliseconds, or `false` if the argument is not a pickup.
function getPickupRespawnInterval(thePickup) end

--- Tells you whether the pickup is out in the world or still waiting to respawn.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/pickup/#ispickupspawned
---@param thePickup pickup
---@return boolean # `true` if it is visible, `false` if it is waiting to respawn or the argument is not a pickup.
function isPickupSpawned(thePickup) end

--- Sets how long the pickup waits before coming back.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/pickup/#setpickuprespawninterval
---@param thePickup pickup The pickup to change.
---@param milliseconds number Respawn interval. Must be `0` or greater.
---@return boolean # `true` on success, `false` if the argument is not a pickup or the interval is negative.
function setPickupRespawnInterval(thePickup, milliseconds) end

--- Makes a player collect the pickup right now, as if they had walked over it.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/pickup/#usepickup
---@param thePickup pickup The pickup to collect.
---@param thePlayer player Who collects it.
---@return boolean # `true` if the pickup was collected, `false` if either argument is invalid.
function usePickup(thePickup, thePlayer) end

--- Sets who is allowed to hear a player.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/voice/#setplayervoicebroadcastto
---@param thePlayer player The player who is talking.
---@param broadcastTo? element|table Who may hear them. A single element, a table of elements, or `nil` to go back to the default: everyone.
---@return boolean # `true` if the list was applied. Returns `false` if the first argument is not a player, if `broadcastTo` is anything other than an element, a table or `nil`, or if voice is not available.
function setPlayerVoiceBroadcastTo(thePlayer, broadcastTo) end

--- Sets who a player will **not** hear.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/voice/#setplayervoiceignorefrom
---@param thePlayer player The player who is listening.
---@param ignoreFrom? element|table Who to stop hearing. A single element, a table of elements, or `nil` to clear the list.
---@return boolean # `true` if the list was applied. Returns `false` if the first argument is not a player, if `ignoreFrom` is anything other than an element, a table or `nil`, or if voice is not available.
function setPlayerVoiceIgnoreFrom(thePlayer, ignoreFrom) end

--- Returns the distance currently in force.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/voice/#getvoicemaxdistance
---@return number # the maximum distance, in game units. Returns `0` when voice is not available.
function getVoiceMaxDistance() end

--- Changes how far a player can be heard, for the whole server.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/voice/#setvoicemaxdistance
---@param distance number Maximum distance, in game units. Must be greater than zero and finite.
---@return boolean # `true` when the new distance was applied. Returns `false`, with an error in the debug output, if voice is not available or the distance is zero, negative, `nan` or infinite.
function setVoiceMaxDistance(distance) end

--- Hashes a password.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#passwordhash
---@param password string
---@return string # the hash, ready to be stored, or `false` if hashing failed (the reason goes to the debug console).
function passwordHash(password) end

--- Checks a password against a hash.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#passwordverify
---@param hash string The stored hash, exactly as `passwordHash` returned it.
---@param password string The password the player typed.
---@return boolean # `true` if the password matches. `false` if it does not, or if the hash is malformed.
function passwordVerify(hash, password) end

--- Tells a player's client to connect to another server.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#redirectplayer
---@param thePlayer player Player to redirect.
---@param serverIP? string Address of the destination server.
---@param serverPort? number Port of the destination server, 0 to 65535.
---@param serverPassword? string Password to connect with, if the destination needs one.
---@return boolean # `true` if the order was sent. Returns `false` if the first argument is not a connected player, and a port outside 0-65535 raises an error and returns `false`.
function redirectPlayer(thePlayer, serverIP, serverPort, serverPassword) end

--- Changes a weapon property for everyone on the server.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/weapon/#setweaponproperty
---@param weapon string|number Weapon id (`0`–`46`) or name.
---@param skill string|number `"poor"`, `"std"`, `"pro"`, or a number from `0` to `3`.
---@param property string Name of the property to change.
---@param value number|boolean A number for the numeric properties, `true`/`false` for the flags.
---@return boolean # `true` if the change was applied. Returns `false` when the weapon has no properties, when the property is read-only, when the value is of the wrong type, or when it falls outside the accepted range.
function setWeaponProperty(weapon, skill, property, value) end

--- Gives the ped a weapon, with ammo.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#giveweapon
---@param thePed ped Ped, or a parent element.
---@param weapon string|number Weapon id (`0`–`46`) or name.
---@param ammo? number Ammo to hand over, `0` to `65535`. Anything above `9999` is capped at `9999`.
---@param setAsCurrent? boolean Leaves the ped holding the weapon straight away.
---@return boolean # `true` if at least one ped got the weapon. An invalid weapon, or ammo outside `0`–`65535`, returns `false`.
function giveWeapon(thePed, weapon, ammo, setAsCurrent) end

--- Takes a weapon away from the ped, or drains part of its ammo.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#takeweapon
---@param thePed ped Ped, or a parent element.
---@param weapon string|number Weapon id (`1`–`46`) or name. Fists cannot be taken away.
---@param ammo? number How many rounds to remove, `0` to `65535`.
---@return boolean # `true` if at least one ped lost the weapon or the ammo. Returns `false` when the ped is not carrying that weapon in the slot.
function takeWeapon(thePed, weapon, ammo) end

--- Empties the ped's inventory.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/ped/#takeallweapons
---@param thePed ped
---@return boolean # `true` if at least one ped was disarmed. Every slot is cleared and the ped falls back to fists.
function takeAllWeapons(thePed) end

--- Tells whether a weapon can be used while flying a jetpack.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/world/#getjetpackweaponenabled
---@param weapon number|string Weapon ID, `1` to `46`, or its name (`"pistol"`, `"deagle"`, `"mp5"`, `"ak47"`, `"m4"`, `"sniper"`, …). Names are case-insensitive.
---@return boolean # `true` if the weapon is allowed while flying, `false` otherwise. An unknown ID or name returns `false` and logs a warning to the debug console.
function getJetpackWeaponEnabled(weapon) end

--- Allows or blocks a weapon while flying a jetpack.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/world/#setjetpackweaponenabled
---@param weapon number|string Weapon ID (`1`–`46`) or name.
---@param enabled boolean `true` allows it, `false` blocks it.
---@return boolean # `true`, or `false` if the weapon is not recognised.
function setJetpackWeaponEnabled(weapon, enabled) end

--- Returns every player who is currently alive.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getaliveplayers
---@return table # a table of player elements, indexed from `1`. When nobody qualifies you get an empty table, never `false`.
function getAlivePlayers() end

--- Returns every player who is not alive.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getdeadplayers
---@return table # a table of player elements, indexed from `1`, empty when nobody qualifies.
function getDeadPlayers() end

--- Reads back a value stored with [`setPlayerAnnounceValue`](#setplayerannouncevalue).
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayerannouncevalue
---@param thePlayer player
---@param key string
---@return string # the stored text. A key that was never written answers with an empty string, so a missing value and an empty value look the same. Returns `false` if the element is not a player.
function getPlayerAnnounceValue(thePlayer, key) end

--- Returns a player's violation record.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayeranticheatviolations
---@param thePlayer player
---@return table # an array of tables, one per kind of violation the player has raised. Returns an empty table when the player has no record, and `false` if the element is not a player.
function getPlayerAnticheatViolations(thePlayer) end

--- Returns how many players are connected right now.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayercount
---@return number # the number of connected players. It is always a number: an empty server answers `0`.
function getPlayerCount() end

--- Returns the network address a player is connected from.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayerip
---@param thePlayer player
---@return string # the address as text. Returns `false` if the element is not a player, or if the connection can no longer be read — which is the case for someone who is already leaving.
function getPlayerIP(thePlayer) end

--- Returns every identifier the server holds for a player's connection.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayeridentifiers
---@param thePlayer player
---@return table # an array of strings, each one prefixed with its kind. Returns an empty table when the connection has no identity yet, and `false` if the element is not a player.
function getPlayerIdentifiers(thePlayer) end

--- Returns how long a player has been standing still.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayeridletime
---@param thePlayer player
---@return number # the number of milliseconds since the player last moved. A player who has not moved at all since joining answers `0`. Returns `false` if the element is not a player.
function getPlayerIdleTime(thePlayer) end

--- Returns the protocol version a player's client is running.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getplayerversion
---@param thePlayer player
---@return string # the version as text, in the form `"0.major.minor"`. Returns `false` if the element is not a player.
function getPlayerVersion(thePlayer) end

--- Picks one connected player at random.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#getrandomplayer
---@return player # a player element, chosen with equal odds among everyone connected. Returns `false` when the server is empty.
function getRandomPlayer() end

--- Reads the exemption currently in force for a player.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#isplayeranticheatenabled
---@param thePlayer player
---@return boolean, string # two values: whether the anticheat is fully active for that player, and the comma-separated list of waived families. A player with no exemption answers `true, ""`.
function isPlayerAnticheatEnabled(thePlayer) end

--- Checks whether a player is currently muted.
---
--- Side: **server** · Trust: **sandboxed**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#isplayermuted
---@param thePlayer player
---@return boolean # `true` if the player is muted, `false` otherwise or if the element is not a player.
function isPlayerMuted(thePlayer) end

--- Kept so that scripts calling it still load.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#resendplayermodinfo
---@param thePlayer player
---@return boolean # always `false`. MTAX does not collect any mod report from clients, so there is nothing to ask for again: the call writes a warning to the debug output and does nothing else. Passing something that is not a player fails the same way.
function resendPlayerModInfo(thePlayer) end

--- Changes the policy of a violation, for the whole server.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setanticheatpolicy
---@param violation string Name from the [catalog](/en/server/anticheat/#violation-catalog).
---@param action string `ignore`, `log`, `warn` or `kick`.
---@param threshold? number Occurrences inside the window before the action fires.
---@param windowMs? number Window length, in milliseconds.
---@return boolean # `true` on success. Returns `false` for an unknown violation or action, or for a negative `threshold`/`windowMs`.
function setAnticheatPolicy(violation, action, threshold, windowMs) end

--- Stores a text value on a player under a key of your choice.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setplayerannouncevalue
---@param thePlayer player Player to store the value on.
---@param key string Name to store it under. Writing the same key again replaces the value.
---@param value string Text to store.
---@return boolean # `true` once the value is stored, `false` if the element is not a player.
function setPlayerAnnounceValue(thePlayer, key, value) end

--- Grants or clears an anticheat exemption for a player.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setplayeranticheatenabled
---@param thePlayer player Player to change.
---@param enabled boolean `true` clears any exemption; `false` grants one.
---@param families? string Comma-separated families to waive. Only read when `enabled` is `false`.
---@return boolean # `true` on success. Returns `false` if the element is not a player or the family list has an unknown name.
function setPlayerAnticheatEnabled(thePlayer, enabled, families) end

--- Marks a player as muted, or lifts the mute.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setplayermuted
---@param thePlayer element Player, or an element above them in the tree.
---@param muted boolean `true` mutes, `false` unmutes.
---@return boolean # `true` if at least one player changed state. Muting someone who is already muted changes nothing and returns `false`, and so does an argument that is not a valid element.
function setPlayerMuted(thePlayer, muted) end

--- Renames a connected player.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#setplayername
---@param thePlayer player Player to rename.
---@param newName string New name, 1 to 22 characters.
---@return boolean # `true` if the rename went through. It returns `false`, without raising an error, when the name is empty or longer than 22 characters, when it contains a character that is not allowed, when it is the name the player already has, or when another connected player is already using it (upper and lower case count as the same name).
function setPlayerName(thePlayer, newName) end

--- Sets or clears the server's join password.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/utility/#setserverpassword
---@param password? string The new password. With no argument, or an empty string, the password is removed.
---@return boolean # `true` if the password was changed, `false` if it is invalid.
function setServerPassword(password) end

--- Asks a player's client to capture their screen and send the image back.
---
--- Side: **server** · Trust: **authoritative**
--- @see https://wiki.mtax.com.br/en/scripting/functions/server/player/#takeplayerscreenshot
---@param thePlayer element Player, or an element above them in the tree.
---@param sizeX number Width of the capture, 1 to 65535.
---@param sizeY number Height of the capture, 1 to 65535.
---@param tag? string Free text handed back with the result — useful to tell several captures apart.
---@param quality? number Image quality, 0 to 100. Higher means a bigger transfer.
---@param maxBandwidth? number Upper limit, in bytes per second, for the transfer. A negative value is treated as `0`.
---@param maxPacketSize? number Size of each chunk the image is split into, 1 to 65535.
---@return boolean # `true` once the request has been sent to at least one player. Returns `false` if the first argument is not a valid element or has no players under it. A size, quality or chunk size outside its range raises an error and returns `false`.
function takePlayerScreenShot(thePlayer, sizeX, sizeY, tag, quality, maxBandwidth, maxPacketSize) end
