---@meta
-- MTAX Lua API — types
-- Generated by mtax-vscode (tools/generate-api.mjs). Do not edit by hand.

---@class account
---@class acl
---@class aclgroup
---@class ban
---@class blip : Blip
---@class browser
---@class building : Building
---@class camera
---@class col
---@class colshape : ColShape
---@class connection : Connection
---@class dff
---@class dui : Dui
---@class effect : Effect
---@class element : Element
---@class file
---@class handling
---@class ifp
---@class light : Light
---@class marker : Marker
---@class matrix : Matrix
---@class object : Object
---@class ped : Ped
---@class pickup : Pickup
---@class player : Player
---@class primitive
---@class projectile : Projectile
---@class querybrowser
---@class querybrowserquery
---@class radararea
---@class request
---@class resource
---@class screensource
---@class searchlight : SearchLight
---@class shader
---@class sound : Sound
---@class sound3d
---@class svg : SVG
---@class team
---@class texture
---@class timer
---@class txd
---@class userdata
---@class vector2 : Vector2
---@class vector3 : Vector3
---@class vector4 : Vector4
---@class vehicle : Vehicle
---@class water : Water
---@class weapon : Weapon
---@class xmlnode


---@class Vector2
---@field x number
---@field y number
---@field length number
---@field squaredLength number
---@field normalized Vector2
---@operator add(Vector2): Vector2
---@operator sub(Vector2): Vector2
---@operator mul(number|Vector2): Vector2
---@operator div(number|Vector2): Vector2
---@operator unm: Vector2
local Vector2 = {}
function Vector2:getLength() end
function Vector2:getSquaredLength() end
function Vector2:getNormalized() end
function Vector2:normalize() end
---@param other Vector2
function Vector2:dot(other) end
function Vector2:getX() end
function Vector2:getY() end
---@param value number
function Vector2:setX(value) end
---@param value number
function Vector2:setY(value) end

---@class Vector3
---@field x number
---@field y number
---@field z number
---@field length number
---@field squaredLength number
---@field normalized Vector3
---@operator add(Vector3): Vector3
---@operator sub(Vector3): Vector3
---@operator mul(number|Vector3): Vector3
---@operator div(number|Vector3): Vector3
---@operator unm: Vector3
local Vector3 = {}
function Vector3:getLength() end
function Vector3:getSquaredLength() end
function Vector3:getNormalized() end
function Vector3:normalize() end
---@param other Vector3
function Vector3:dot(other) end
---@param other Vector3
---@return Vector3
function Vector3:cross(other) end
--- Moeller-Trumbore segment/triangle intersection. Returns the hit point, or `false`.
---@param dir Vector3
---@param v0 Vector3
---@param v1 Vector3
---@param v2 Vector3
---@return Vector3|boolean
function Vector3:intersectsSegmentTriangle(dir, v0, v1, v2) end
function Vector3:getX() end
function Vector3:getY() end
function Vector3:getZ() end
---@param value number
function Vector3:setX(value) end
---@param value number
function Vector3:setY(value) end
---@param value number
function Vector3:setZ(value) end

---@class Vector4 : Vector3
---@field w number
local Vector4 = {}
function Vector4:getW() end
---@param value number
function Vector4:setW(value) end

---@class Matrix
---@field position Vector3
---@field rotation Vector3
---@field forward Vector3
---@field right Vector3
---@field up Vector3
local Matrix = {}
---@return Vector3
function Matrix:getPosition() end
---@param position Vector3
function Matrix:setPosition(position) end
---@return Vector3
function Matrix:getRotation() end
---@param rotation Vector3
function Matrix:setRotation(rotation) end
---@param v Vector3
---@return Vector3
function Matrix:transformPosition(v) end
---@param v Vector3
---@return Vector3
function Matrix:transformDirection(v) end
---@return Matrix
function Matrix:inverse() end

---@param x number|table|nil
---@param y? number
---@return Vector2
function Vector2(x, y) end
---@param x number|table|nil
---@param y? number
---@param z? number
---@return Vector3
function Vector3(x, y, z) end
---@param x number|table|nil
---@param y? number
---@param z? number
---@param w? number
---@return Vector4
function Vector4(x, y, z, w) end
---@param position? Vector3
---@param rotation? Vector3
---@return Matrix
function Matrix(position, rotation) end


--- Root of the element tree. A handler attached here catches an event wherever it came from.
--- Side: **shared**
---@type element
root = nil

--- This resource's own root element. Everything it creates hangs off it.
--- Side: **shared**
---@type element
resourceRoot = nil

--- The player at this machine.
--- Side: **client**
---@type player
localPlayer = nil

--- Inside an event handler: the element the event came from.
--- Side: **shared**
---@type element
source = nil

--- Inside a handler for a remote event: the player who triggered it. `nil` otherwise — always validate it.
--- Side: **server**
---@type player
client = nil

--- Inside an event handler: the name of the running event.
--- Side: **shared**
---@type string
eventName = nil

--- The resource whose script called `triggerEvent`. `nil` when the engine fired it.
--- Side: **shared**
---@type resource
sourceResource = nil

--- That resource's root element, `nil` in the same cases.
--- Side: **shared**
---@type element
sourceResourceRoot = nil

--- Proxy table for calling another resource's exported functions: `exports.bank:getBalance(player)`.
--- Side: **shared**
---@type table
exports = nil
